/*
 * generated by Xtext
 */
package net.zehrer.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WordsUiModule extends net.zehrer.xtext.ui.AbstractWordsUiModule {
	public WordsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
