/*******************************************************************************
 * Copyright (c) 2009 Stephan Zehrer and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Stephan Zehrer - initial API and implementation
 *******************************************************************************/

package net.zehrer.no2.model.factory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.ecore.provider.EcoreItemProviderAdapterFactory;
import org.eclipse.emf.edit.provider.ReflectiveItemProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support
 * Viewers. The adapters generated by this factory convert EMF adapter
 * notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The
 * adapters also support Eclipse property sheets. Note that most of the adapters
 * are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * 
 * @generated
 */
public class ModelItemProviderAdapterFactory extends EcoreItemProviderAdapterFactory {

	/**
	 * This constructs an instance.
	 */
	public ModelItemProviderAdapterFactory() {
		super();
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.ecore.EObject}. 
	 */
	@Override
	public Adapter createEObjectAdapter() {
		if (eObjectItemProvider == null) {
			//TODO: add here a new ItemProvider for EObjects
			eObjectItemProvider = new ReflectiveItemProvider(this);
		}

		return eObjectItemProvider;
	}

}
