/*
* generated by Xtext
*/
package net.zehrer.no2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class TexlikTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
