/*
 * generated by Xtext
 */
package net.zehrer.no2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TexlikRuntimeModule extends net.zehrer.no2.AbstractTexlikRuntimeModule {

}
