/*
* generated by Xtext
*/
package net.zehrer.no2.ui.contentassist;

import net.zehrer.no2.ui.contentassist.AbstractTexlikProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TexlikProposalProvider extends AbstractTexlikProposalProvider {

}
