/*
* generated by Xtext
*/
package net.zehrer.xtext.ui.contentassist;

import net.zehrer.xtext.ui.contentassist.AbstractWordsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WordsProposalProvider extends AbstractWordsProposalProvider {

}
