<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test"
    nsURI="http://zehrer.net/test" nsPrefix="zt">
  <eSubpackages name="generic1" nsURI="http://zehrer.net/test/generic1" nsPrefix="ztg1">
    <eClassifiers xsi:type="ecore:EClass" name="BasicElement">
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eGenericType eTypeParameter="#//generic1/BasicElement/T"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntBasicElement">
      <eGenericSuperTypes eClassifier="#//generic1/BasicElement">
        <eTypeArguments eClassifier="#//generic1/Interger1"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Comparable2" instanceClassName="java.lang.Comparable"
        abstract="true" interface="true">
      <eTypeParameters name="T"/>
      <eOperations name="compareTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eParameters name="other">
          <eGenericType eTypeParameter="#//generic1/Comparable2/T"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Comparable1" instanceClassName="java.lang.Comparable">
      <eTypeParameters name="T"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Interger1" instanceClassName="java.lang.Integer"/>
  </eSubpackages>
</ecore:EPackage>
