<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="interval"
    nsURI="http://zehrer.net/common/interval/1.0" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="EInterval" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//IComparable">
        <eTypeArguments eTypeParameter="#//EInterval/T"/>
      </eBounds>
    </eTypeParameters>
    <eOperations name="intersects" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other">
        <eGenericType eClassifier="#//EInterval">
          <eTypeArguments eTypeParameter="#//EInterval/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="intersect">
      <eGenericType eClassifier="#//EInterval">
        <eTypeArguments eTypeParameter="#//EInterval/T"/>
      </eGenericType>
      <eParameters name="other">
        <eGenericType eClassifier="#//EInterval">
          <eTypeArguments eTypeParameter="#//EInterval/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="isBelow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value">
        <eGenericType eTypeParameter="#//EInterval/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="isAbove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value">
        <eGenericType eTypeParameter="#//EInterval/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other">
        <eGenericType eClassifier="#//EInterval">
          <eTypeArguments eTypeParameter="#//EInterval/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="includes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value">
        <eGenericType eTypeParameter="#//EInterval/T"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerLimit" lowerBound="1">
      <eGenericType eTypeParameter="#//EInterval/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperLimit" lowerBound="1">
      <eGenericType eTypeParameter="#//EInterval/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//IComparable">
      <eTypeArguments eClassifier="#//EInterval">
        <eTypeArguments eTypeParameter="#//EInterval/T"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EIntInterval">
    <eOperations name="intersects" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//EIntInterval"/>
    </eOperations>
    <eOperations name="intersect" eType="#//EIntInterval">
      <eParameters name="other" eType="#//EIntInterval"/>
    </eOperations>
    <eOperations name="isBelow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eOperations>
    <eOperations name="isAbove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eOperations>
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//EIntInterval"/>
    </eOperations>
    <eOperations name="includes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eOperations>
    <eOperations name="isSubsetOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="value" eType="#//EIntInterval"/>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="leftComplementTo" eType="#//EIntInterval">
      <eParameters name="other" eType="#//EIntInterval"/>
    </eOperations>
    <eOperations name="rightComplementTo" eType="#//EIntInterval">
      <eParameters name="other" eType="#//EIntInterval"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        transient="true"/>
    <eGenericSuperTypes eClassifier="#//IComparable">
      <eTypeArguments eClassifier="#//EIntInterval"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComparable" instanceClassName="java.lang.Comparable"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eOperations name="compareTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="other">
        <eGenericType eTypeParameter="#//IComparable/T"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
</ecore:EPackage>
