/*
 * generated by Xtext
 */
package net.zehrer.no2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TexlikUiModule extends net.zehrer.no2.ui.AbstractTexlikUiModule {
	public TexlikUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
