grammar net.zehrer.xtext.Words hidden(WS)

// with org.eclipse.xtext.common.Terminals

generate words "http://www.zehrer.net/xtext/Words"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore


Model :
  (elements+=Object)*;
 
// -----

terminal ID : '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
terminal WS	: (' '|'\t'|'\r'|'\n')+;

// -----

Object: 
  Word | Term;
  
Word: 
  name=ID;

Term:
  "'" name=Text "'";  
  
Text:
 ID (ID)*;