/*
 * generated by Xtext
 */
package net.zehrer.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WordsRuntimeModule extends net.zehrer.xtext.AbstractWordsRuntimeModule {

}
